import { AppProps } from "next/app";
import Head from "next/head";
import { Provider } from "react-redux";
import { PersistGate } from "redux-persist/integration/react";
import { store, persistor } from "../redux/store";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import "../styles/globals.css";
import organzation from "../languages/en/texts/organization";
import PageWrapper from "../components/page-wrapper";

config.autoAddCss = false;

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}>
      <PersistGate persistor={persistor}>
        <Head>
          <title>{`${organzation.name.short} (${organzation.name.full})`}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <PageWrapper>
          <Component {...pageProps} />
        </PageWrapper>
      </PersistGate>
    </Provider>
  );
}

export default MyApp;
